name: medipot_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  get: ^4.6.5
  infinite_scroll_pagination: ^3.2.0
  firebase_core: ^2.14.0
  firebase_dynamic_links: ^5.3.2
  share_plus: ^7.0.2
  uni_links: ^0.5.1
  firebase_analytics: ^10.8.10
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.1
  kakao_flutter_sdk_user: ^1.5.0
  webview_flutter: ^4.2.4
  image_picker: ^1.0.4
  dio: ^5.3.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/image/logo.png
    - assets/image/kakao_logo.png
    - assets/image/heart.png
    - assets/image/heart_fill.png
    - assets/image/logo_text.png
    - assets/image/hours.png
    - assets/image/search.png
    - assets/image/sns/instagram.png
    - assets/image/sns/blog-text.png
    - assets/image/sns/blog-pencil.png

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
